/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleArticlesRouteImport } from './routes/$locale/articles'
import { Route as LocaleArticlesIndexRouteImport } from './routes/$locale/articles.index'
import { Route as LocaleArticlesSlugRouteImport } from './routes/$locale/articles.$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleArticlesRoute = LocaleArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleArticlesIndexRoute = LocaleArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleArticlesRoute,
} as any)
const LocaleArticlesSlugRoute = LocaleArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/articles': typeof LocaleArticlesRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles/': typeof LocaleArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles': typeof LocaleArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/articles': typeof LocaleArticlesRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles/': typeof LocaleArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/articles'
    | '/$locale/'
    | '/$locale/articles/$slug'
    | '/$locale/articles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale' | '/$locale/articles/$slug' | '/$locale/articles'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/articles'
    | '/$locale/'
    | '/$locale/articles/$slug'
    | '/$locale/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/articles': {
      id: '/$locale/articles'
      path: '/articles'
      fullPath: '/$locale/articles'
      preLoaderRoute: typeof LocaleArticlesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/articles/': {
      id: '/$locale/articles/'
      path: '/'
      fullPath: '/$locale/articles/'
      preLoaderRoute: typeof LocaleArticlesIndexRouteImport
      parentRoute: typeof LocaleArticlesRoute
    }
    '/$locale/articles/$slug': {
      id: '/$locale/articles/$slug'
      path: '/$slug'
      fullPath: '/$locale/articles/$slug'
      preLoaderRoute: typeof LocaleArticlesSlugRouteImport
      parentRoute: typeof LocaleArticlesRoute
    }
  }
}

interface LocaleArticlesRouteChildren {
  LocaleArticlesSlugRoute: typeof LocaleArticlesSlugRoute
  LocaleArticlesIndexRoute: typeof LocaleArticlesIndexRoute
}

const LocaleArticlesRouteChildren: LocaleArticlesRouteChildren = {
  LocaleArticlesSlugRoute: LocaleArticlesSlugRoute,
  LocaleArticlesIndexRoute: LocaleArticlesIndexRoute,
}

const LocaleArticlesRouteWithChildren = LocaleArticlesRoute._addFileChildren(
  LocaleArticlesRouteChildren,
)

interface LocaleRouteChildren {
  LocaleArticlesRoute: typeof LocaleArticlesRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleArticlesRoute: LocaleArticlesRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
